[search]
default="https://duckduckgo.com/?q=${q}"

[bookmarks]
angular = 'https://angular.io/?search=${q}'
bootsnipp ='https://bootsnipp.com/search?q=${q}'
bundlephobia = 'https://bundlephobia.com/result?p=${q}'
caniuse ='https://caniuse.com/#search=${q}'
codepen ='https://codepen.io/search?q=${q}'
compassdoc = 'http://compass-style.org/search?q=${q}'
cssflow ='http://www.cssflow.com/search?q=${q}'
dartlang = 'https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:${q}'
fontello = 'http://fontello.com/#search=${q}'
github = 'https://github.com/search?q=${q}'
html5please ='https://html5please.com/#${q}'
jquery = 'https://api.jquery.com/?s=${q}'
lodash = 'https://devdocs.io/lodash/index#${q}'
mdn ='https://developer.mozilla.org/search?q=${q}'
npmjs ='https://www.npmjs.com/search?q=${q}'
packagephobia ='https://packagephobia.now.sh/result?p=${q}'
qunit ='https://api.qunitjs.com/?s=${q}'
stackoverflow ='https://stackoverflow.com/search?q=${q}'
unheap = 'http://www.unheap.com/?s=${q}'
