[search]
default='https://duckduckgo.com/?q=%s'

[bookmarks]
angular = 'https://angular.io/?search=%s'
bootsnipp ='https://bootsnipp.com/search?q=%s'
bundlephobia = 'https://bundlephobia.com/result?p=%s'
caniuse ='https://caniuse.com/#search=%s'
codepen ='https://codepen.io/search?q=%s'
compassdoc = 'https://compass-style.org/search?q=%s'
cssflow ='https://www.cssflow.com/search?q=%s'
dartlang = 'https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:%s'
fontello = 'https://fontello.com/#search=%s'
github = 'https://github.com/search?q=%s'
html5please ='https://html5please.com/#%s'
jquery = 'https://api.jquery.com/?s=%s'
lodash = 'https://devdocs.io/lodash/index#%s'
mdn ='https://developer.mozilla.org/search?q=%s'
npmjs ='https://www.npmjs.com/search?q=%s'
packagephobia ='https://packagephobia.now.sh/result?p=%s'
qunit ='https://api.qunitjs.com/?s=%s'
stackoverflow ='https://stackoverflow.com/search?q=%s'
unheap = 'https://www.unheap.com/?s=%s'

# Social sites
facebook = 'https://www.facebook.com/search/top/?q=%s'
hackernews = 'https://hndex.org/?q=%s'
reddit = 'https://www.reddit.com/r/%s'
twitter = 'https://twitter.com/search?q=%s'
youtube = 'https://www.youtube.com/results?search_query=%s'

# Linux Packages
flathub = 'https://flathub.org/apps/search/%s'

# Programming
amo = 'https://addons.mozilla.org/en-US/firefox/search/?q=%s'
cratesio = 'https://crates.io/search?q=%s'
docsrs = 'https://docs.rs/releases/search?query=%s'
maven = 'https://search.maven.org/search?q=%s'
npm = 'https://www.npmjs.com/search?q=%s'

[alias]
crate = 'cratesio'
fb = 'facebook'
fh = 'flathub'
hn = 'hackernews'
r = 'reddit'
t = 'twitter'
yt = 'youtube'
